using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace tp_final //No la usamos para el programa era simplemente para probar cosas
{
    public class ClassDataGrafoTest
    {
        public List<string> listaNodos;
        public List<string> listaNodosPartida;
        public List<string> listaNodosDestino;
        public List<float> listaNodosPeso;

        public ClassDataGrafoTest() 
        {
            listaNodos = new List<string>();
            listaNodosPartida = new List<string>();
            listaNodosDestino = new List<string>();
            listaNodosPeso = new List<float>();

            CargarListas();
        }

        public void CargarListas()
        {
            listaNodos.Add("comuna 1");
            listaNodos.Add("comuna 2");
            listaNodos.Add("comuna 3");
            listaNodos.Add("comuna 4");
            listaNodos.Add("comuna 5");
            listaNodos.Add("comuna 6");
            listaNodos.Add("comuna 7");
            listaNodos.Add("comuna 8");
            listaNodos.Add("comuna 9"); //deposito
            listaNodos.Add("comuna 10");
            listaNodos.Add("comuna 11");
            listaNodos.Add("comuna 12");
            listaNodos.Add("comuna 13");
            listaNodos.Add("comuna 14");
            listaNodos.Add("comuna 15");
            listaNodos.Add("la matanza");
            listaNodos.Add("lomas de zamora");
            listaNodos.Add("moron");
            listaNodos.Add("san isidro");
            listaNodos.Add("san martin");
            listaNodos.Add("tres de febrero");
            listaNodos.Add("vicente lopez");
            listaNodos.Add("avellaneda");
            listaNodos.Add("lanus");
            listaNodosPartida.Add("san isidro");
            listaNodosPartida.Add("san isidro");
            listaNodosPartida.Add("san martin");
            listaNodosPartida.Add("san martin");
            listaNodosPartida.Add("san martin");
            listaNodosPartida.Add("san martin");
            listaNodosPartida.Add("vicente lopez");
            listaNodosPartida.Add("vicente lopez");
            listaNodosPartida.Add("tres de febrero");
            listaNodosPartida.Add("tres de febrero");
            listaNodosPartida.Add("tres de febrero");
            listaNodosPartida.Add("tres de febrero");
            listaNodosPartida.Add("tres de febrero");
            listaNodosPartida.Add("moron");
            listaNodosPartida.Add("la matanza");
            listaNodosPartida.Add("la matanza");
            listaNodosPartida.Add("la matanza");
            listaNodosPartida.Add("lomas de zamora");
            listaNodosPartida.Add("lomas de zamora");
            listaNodosPartida.Add("lanus");
            listaNodosPartida.Add("lanus");
            listaNodosPartida.Add("lanus");
            listaNodosPartida.Add("avellaneda");
            listaNodosPartida.Add("comuna 1");
            listaNodosPartida.Add("comuna 1");
            listaNodosPartida.Add("comuna 1");
            listaNodosPartida.Add("comuna 2");
            listaNodosPartida.Add("comuna 2");
            listaNodosPartida.Add("comuna 2");
            listaNodosPartida.Add("comuna 3");
            listaNodosPartida.Add("comuna 3");
            listaNodosPartida.Add("comuna 4");
            listaNodosPartida.Add("comuna 4");
            listaNodosPartida.Add("comuna 4");
            listaNodosPartida.Add("comuna 5");
            listaNodosPartida.Add("comuna 5");
            listaNodosPartida.Add("comuna 5");
            listaNodosPartida.Add("comuna 6");
            listaNodosPartida.Add("comuna 6");
            listaNodosPartida.Add("comuna 6");
            listaNodosPartida.Add("comuna 7");
            listaNodosPartida.Add("comuna 7");
            listaNodosPartida.Add("comuna 7");
            listaNodosPartida.Add("comuna 7");
            listaNodosPartida.Add("comuna 8");
            listaNodosPartida.Add("comuna 9");
            listaNodosPartida.Add("comuna 10");
            listaNodosPartida.Add("comuna 11");
            listaNodosPartida.Add("comuna 11");
            listaNodosPartida.Add("comuna 12");
            listaNodosPartida.Add("comuna 12");
            listaNodosPartida.Add("comuna 13");
            listaNodosPartida.Add("comuna 13");
            listaNodosPartida.Add("comuna 14");
            listaNodosDestino.Add("vicente lopez");
            listaNodosDestino.Add("san martin");
            listaNodosDestino.Add("comuna 11");
            listaNodosDestino.Add("comuna 12");
            listaNodosDestino.Add("tres de febrero");
            listaNodosDestino.Add("vicente lopez");
            listaNodosDestino.Add("comuna 13");
            listaNodosDestino.Add("comuna 12");
            listaNodosDestino.Add("moron");
            listaNodosDestino.Add("la matanza");
            listaNodosDestino.Add("comuna 9");
            listaNodosDestino.Add("comuna 10");
            listaNodosDestino.Add("comuna 11");
            listaNodosDestino.Add("la matanza");
            listaNodosDestino.Add("lomas de zamora");
            listaNodosDestino.Add("comuna 8");
            listaNodosDestino.Add("comuna 9");
            listaNodosDestino.Add("lanus");
            listaNodosDestino.Add("comuna 8");
            listaNodosDestino.Add("avellaneda");
            listaNodosDestino.Add("comuna 8");
            listaNodosDestino.Add("comuna 4");
            listaNodosDestino.Add("comuna 4");
            listaNodosDestino.Add("comuna 2");
            listaNodosDestino.Add("comuna 3");
            listaNodosDestino.Add("comuna 4");
            listaNodosDestino.Add("comuna 14");
            listaNodosDestino.Add("comuna 5");
            listaNodosDestino.Add("comuna 3");
            listaNodosDestino.Add("comuna 5");
            listaNodosDestino.Add("comuna 4");
            listaNodosDestino.Add("comuna 5");
            listaNodosDestino.Add("comuna 7");
            listaNodosDestino.Add("comuna 8");
            listaNodosDestino.Add("comuna 14");
            listaNodosDestino.Add("comuna 6");
            listaNodosDestino.Add("comuna 7");
            listaNodosDestino.Add("comuna 7");
            listaNodosDestino.Add("comuna 11");
            listaNodosDestino.Add("comuna 15");
            listaNodosDestino.Add("comuna 11");
            listaNodosDestino.Add("comuna 8");
            listaNodosDestino.Add("comuna 9");
            listaNodosDestino.Add("comuna 10");
            listaNodosDestino.Add("comuna 9");
            listaNodosDestino.Add("comuna 10");
            listaNodosDestino.Add("comuna 11");
            listaNodosDestino.Add("comuna 15");
            listaNodosDestino.Add("comuna 12");
            listaNodosDestino.Add("comuna 15");
            listaNodosDestino.Add("comuna 13");
            listaNodosDestino.Add("comuna 15");
            listaNodosDestino.Add("comuna 14");
            listaNodosDestino.Add("comuna 15");
            listaNodosPeso.Add(18);
            listaNodosPeso.Add((float)5.9);
            listaNodosPeso.Add((float)5.4);
            listaNodosPeso.Add((float)7.1);
            listaNodosPeso.Add(11);
            listaNodosPeso.Add(5);
            listaNodosPeso.Add((float)6.2);
            listaNodosPeso.Add(11);
            listaNodosPeso.Add(12);
            listaNodosPeso.Add((float)8.9);
            listaNodosPeso.Add((float)5.1);
            listaNodosPeso.Add((float)3.7);
            listaNodosPeso.Add((float)6.9);
            listaNodosPeso.Add(20);
            listaNodosPeso.Add(18);
            listaNodosPeso.Add((float)6.8);
            listaNodosPeso.Add((float)9.7);
            listaNodosPeso.Add(15);
            listaNodosPeso.Add((float)6.6);
            listaNodosPeso.Add((float)8.8);
            listaNodosPeso.Add((float)7.8);
            listaNodosPeso.Add((float)4.4);
            listaNodosPeso.Add((float)4.5);
            listaNodosPeso.Add((float)4.7);
            listaNodosPeso.Add((float)6.3);
            listaNodosPeso.Add((float)3.6);
            listaNodosPeso.Add((float)4.9);
            listaNodosPeso.Add((float)7.3);
            listaNodosPeso.Add((float)2.9);
            listaNodosPeso.Add((float)4.1);
            listaNodosPeso.Add((float)6.3);
            listaNodosPeso.Add((float)7.5);
            listaNodosPeso.Add((float)7.7);
            listaNodosPeso.Add((float)6.4);
            listaNodosPeso.Add((float)3.2);
            listaNodosPeso.Add((float)4.8);
            listaNodosPeso.Add(3);
            listaNodosPeso.Add((float)8.6);
            listaNodosPeso.Add((float)4.4);
            listaNodosPeso.Add(14);
            listaNodosPeso.Add((float)6.2);
            listaNodosPeso.Add((float)7.1);
            listaNodosPeso.Add((float)7.5);
            listaNodosPeso.Add((float)8.6);
            listaNodosPeso.Add((float)4.9);
            listaNodosPeso.Add((float)2.7);
            listaNodosPeso.Add((float)7.6);
            listaNodosPeso.Add((float)7.6);
            listaNodosPeso.Add((float)6.3);
            listaNodosPeso.Add((float)3.9);
            listaNodosPeso.Add(6);
            listaNodosPeso.Add((float)4.6);
            listaNodosPeso.Add((float)5.1);
        }
    }
}
